name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/checkout@v2
      - name: Install Requirements
        run: pip install -r requirements.txt -r test-requirements.txt
      - name: Run Tox
        run: tox -e py
      - name: Run Flake8
        run: flake8 src tests
      - name: Run Pylint
        run: pylint -rn src tests --rcfile=tox.ini
